{
 "title": "sensor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "nodered",
     "rawSql": "SELECT data FROM nodered.sensor WHERE sensor = 'Sensor01_temperature' ORDER BY id DESC LIMIT 1;"
    },
    {
     "dataset": "nodered",
     "rawSql": "SELECT data FROM nodered.sensor WHERE sensor = 'Sensor02_temperature' ORDER BY id DESC LIMIT 1;"
    },
    {
     "dataset": "nodered",
     "rawSql": "SELECT data FROM nodered.sensor WHERE sensor = 'Sensor01_temperature' ORDER BY id DESC LIMIT 1;"
    },
    {
     "dataset": "nodered",
     "rawSql": "SELECT data FROM nodered.sensor WHERE sensor = 'Sensor01_humidity' ORDER BY id DESC LIMIT 1;"
    },
    {
     "rawSql": "SELECT data FROM nodered.sensor WHERE sensor = 'Sensor02_humidity' ORDER BY id DESC LIMIT 1;"
    },
    {
     "rawSql": "SELECT data FROM nodered.sensor WHERE sensor = 'Sensor03_humidity' ORDER BY id DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "nodered",
     "rawSql": "SELECT datetime, data FROM nodered.sensor WHERE sensor = 'Sensor01_temperature' "
    },
    {
     "dataset": "nodered",
     "rawSql": "SELECT datetime, data FROM nodered.sensor WHERE sensor = 'Sensor02_temperature' "
    },
    {
     "dataset": "nodered",
     "rawSql": "SELECT datetime, data FROM nodered.sensor WHERE sensor = 'Sensor03_temperature' "
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "nodered",
     "rawSql": "SELECT datetime, data, sensor FROM nodered.sensor WHERE sensor = 'SensorCO2_co2' "
    }
   ]
  },
  {
   "title": "Влажность",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "nodered",
     "rawSql": "SELECT datetime, data FROM nodered.sensor WHERE sensor = 'Sensor02_humidity' "
    },
    {
     "dataset": "nodered",
     "rawSql": "SELECT datetime, data FROM nodered.sensor WHERE sensor = 'Sensor03_humidity'"
    },
    {
     "rawSql": "SELECT datetime, data FROM nodered.sensor WHERE sensor = 'Sensor01_humidity' "
    }
   ]
  }
 ]
}